export type KniznicaItemType = "skill" | "prompt" | "info" | "tool";

export interface KniznicaItem {
  id: string;
  title: string;
  category: string;
  description: string;
  url?: string;
  tags: string[];
  type: KniznicaItemType;
  dateAdded: string;
  collection?: string;
}

export interface KniznicaCollection {
  id: string;
  title: string;
  description: string;
  icon: string;
  color: string;
  dateAdded: string;
  items: KniznicaItem[];
}

export const kniznicaCollections: KniznicaCollection[] = [
  {
    id: "claude-skills-prompts-1",
    title: "Claude Skills Prompts — Kolekcia 1",
    description: "42 kurátorských Claude skills z oblasti UI, marketingu, výskumu, médií, kódovania a viac. Zdroj: Claude Skills PDF, jún 2026.",
    icon: "⚡",
    color: "#e07b39",
    dateAdded: "2026-06-04",
    items: [
      {
        id: "frontend-design",
        title: "Frontend Design",
        category: "UI Design",
        description: "Creates bold, non-generic frontend interfaces that avoid typical AI-looking UI.",
        url: "https://github.com/anthropics/skills/tree/main/skills/frontend-design",
        tags: ["UI", "frontend", "design"],
        type: "skill",
        dateAdded: "2026-06-04",
        collection: "claude-skills-prompts-1",
      },
      {
        id: "color-expert",
        title: "Color Expert",
        category: "Color / Branding",
        description: "Optimizes color palettes, accessibility, contrast, OKLCH/OKLAB systems.",
        url: "https://github.com/meodai/skill.color-expert",
        tags: ["farby", "branding", "accessibility", "OKLCH"],
        type: "skill",
        dateAdded: "2026-06-04",
        collection: "claude-skills-prompts-1",
      },
      {
        id: "hand-drawn-diagrams",
        title: "Hand-Drawn Diagrams",
        category: "Diagram / Visual Content",
        description: "Creates editable Excalidraw-style diagrams and exports.",
        url: "https://github.com/muthuishere/hand-drawn-diagrams",
        tags: ["diagramy", "Excalidraw", "vizuály"],
        type: "skill",
        dateAdded: "2026-06-04",
        collection: "claude-skills-prompts-1",
      },
      {
        id: "claude-design-skills",
        title: "ClaudeDesign Skills",
        category: "3D / Motion Design",
        description: "Supports Three.js, GSAP, Framer Motion, Lottie, and Spline.",
        url: "https://github.com/freshtechbro/claudedesignskills",
        tags: ["3D", "Three.js", "GSAP", "animácia", "Framer Motion"],
        type: "skill",
        dateAdded: "2026-06-04",
        collection: "claude-skills-prompts-1",
      },
      {
        id: "nothing-design-skill",
        title: "Nothing Design Skill",
        category: "UI Style System",
        description: "Generates interfaces inspired by Nothing Phone aesthetics.",
        url: "https://github.com/jqueryscript/awesome-claude-code",
        tags: ["UI", "Nothing Phone", "design system"],
        type: "skill",
        dateAdded: "2026-06-04",
        collection: "claude-skills-prompts-1",
      },
      {
        id: "canvas-design",
        title: "Canvas Design",
        category: "Poster / Static Design",
        description: "Creates posters, PNGs, PDFs, and static campaign visuals.",
        url: "https://github.com/anthropics/skills/tree/main/skills/canvas-design",
        tags: ["poster", "PNG", "PDF", "kampane"],
        type: "skill",
        dateAdded: "2026-06-04",
        collection: "claude-skills-prompts-1",
      },
      {
        id: "charlie-hills-social-media",
        title: "Charlie Hills Social Media",
        category: "Social Media System",
        description: "Complete content ecosystem for posts, reels, thumbnails, and analytics.",
        url: "https://github.com/charlie947/social-media-skills",
        tags: ["social media", "reels", "thumbnails", "analytika"],
        type: "skill",
        dateAdded: "2026-06-04",
        collection: "claude-skills-prompts-1",
      },
      {
        id: "voice-builder",
        title: "Voice Builder",
        category: "Brand Voice",
        description: "Analyzes samples to generate consistent brand voice documents.",
        url: "https://github.com/charlie947/social-media-skills/tree/main/skills/voice-builder",
        tags: ["brand voice", "copywriting", "konzistentnosť"],
        type: "skill",
        dateAdded: "2026-06-04",
        collection: "claude-skills-prompts-1",
      },
      {
        id: "reels-scripting",
        title: "Reels Scripting",
        category: "Reels / TikTok",
        description: "Creates high-performing reel scripts in your tone.",
        url: "https://github.com/charlie947/social-media-skills/tree/main/skills/reels-scripting",
        tags: ["reels", "TikTok", "scripting"],
        type: "skill",
        dateAdded: "2026-06-04",
        collection: "claude-skills-prompts-1",
      },
      {
        id: "post-scorer",
        title: "Post Scorer",
        category: "Social Analytics",
        description: "Scores posts using past content performance.",
        url: "https://github.com/charlie947/social-media-skills/tree/main/skills/post-scorer",
        tags: ["analytika", "scoring", "obsah"],
        type: "skill",
        dateAdded: "2026-06-04",
        collection: "claude-skills-prompts-1",
      },
      {
        id: "youtube-thumbnail",
        title: "YouTube Thumbnail",
        category: "YouTube Design",
        description: "Converts titles into high CTR thumbnail prompts.",
        url: "https://github.com/charlie947/social-media-skills/tree/main/skills/youtube-thumbnail",
        tags: ["YouTube", "thumbnail", "CTR"],
        type: "skill",
        dateAdded: "2026-06-04",
        collection: "claude-skills-prompts-1",
      },
      {
        id: "hook-generator",
        title: "Hook Generator",
        category: "Copywriting / Hook",
        description: "Creates hooks using PAS, AIDA, BAB, STAR, and SLAY frameworks.",
        url: "https://github.com/charlie947/social-media-skills/tree/main/skills/hook-generator",
        tags: ["copywriting", "hook", "PAS", "AIDA", "BAB"],
        type: "skill",
        dateAdded: "2026-06-04",
        collection: "claude-skills-prompts-1",
      },
      {
        id: "twitter-algorithm-optimizer",
        title: "Twitter Algorithm Optimizer",
        category: "X Growth",
        description: "Improves tweets using ranking signal insights.",
        url: "https://github.com/ComposioHQ/awesome-claude-skills",
        tags: ["Twitter", "X", "algoritmus", "rast"],
        type: "skill",
        dateAdded: "2026-06-04",
        collection: "claude-skills-prompts-1",
      },
      {
        id: "marketing-module",
        title: "Marketing Module",
        category: "Marketing System",
        description: "Covers SEO, CRO, growth, content, and sales intelligence.",
        url: "https://github.com/alirezarezvani/claude-skills/tree/main/marketing-skill",
        tags: ["marketing", "SEO", "CRO", "sales", "growth"],
        type: "skill",
        dateAdded: "2026-06-04",
        collection: "claude-skills-prompts-1",
      },
      {
        id: "marketing-skills",
        title: "Marketing Skills",
        category: "Growth / Copy / SEO",
        description: "Supports analytics, ad creatives, SEO, and scaling.",
        url: "https://github.com/coreyhaines31/marketingskills",
        tags: ["marketing", "SEO", "reklamy", "analytika"],
        type: "skill",
        dateAdded: "2026-06-04",
        collection: "claude-skills-prompts-1",
      },
      {
        id: "email-marketing-bible",
        title: "Email Marketing Bible",
        category: "Email Marketing",
        description: "Builds stronger lifecycle and retention email systems.",
        url: "https://github.com/CosmoBlk/email-marketing-bible",
        tags: ["email", "lifecycle", "retencia"],
        type: "skill",
        dateAdded: "2026-06-04",
        collection: "claude-skills-prompts-1",
      },
      {
        id: "competitive-ads-extractor",
        title: "Competitive Ads Extractor",
        category: "Ads Research",
        description: "Analyzes competitor ad messaging and creatives.",
        url: "https://github.com/ComposioHQ/awesome-claude-skills",
        tags: ["reklamy", "konkurencia", "výskum"],
        type: "skill",
        dateAdded: "2026-06-04",
        collection: "claude-skills-prompts-1",
      },
      {
        id: "social-media-research",
        title: "Social Media Research",
        category: "Market Research",
        description: "Tracks Reddit and X discussions for audience insights.",
        url: "https://github.com/skainguyen1412/social-media-research-skill",
        tags: ["výskum", "Reddit", "X", "audience"],
        type: "skill",
        dateAdded: "2026-06-04",
        collection: "claude-skills-prompts-1",
      },
      {
        id: "daydream",
        title: "Daydream",
        category: "Knowledge Mining",
        description: "Finds hidden patterns and idea clusters.",
        url: "https://github.com/glebis/claude-skills/tree/main/daydream",
        tags: ["nápady", "vzory", "knowledge mining"],
        type: "skill",
        dateAdded: "2026-06-04",
        collection: "claude-skills-prompts-1",
      },
      {
        id: "humanizer",
        title: "Humanizer",
        category: "Writing Cleanup",
        description: "Refines AI-generated writing into natural prose.",
        url: "https://github.com/blader/humanizer",
        tags: ["písanie", "AI text", "prirodzený štýl"],
        type: "skill",
        dateAdded: "2026-06-04",
        collection: "claude-skills-prompts-1",
      },
      {
        id: "anything-to-notebooklm",
        title: "Anything to NotebookLM",
        category: "Content Repurposing",
        description: "Transforms PDFs and articles into podcasts and quizzes.",
        url: "https://github.com/joeseesun/anything-to-notebooklm",
        tags: ["PDF", "podcast", "kvízy", "NotebookLM"],
        type: "skill",
        dateAdded: "2026-06-04",
        collection: "claude-skills-prompts-1",
      },
      {
        id: "deep-research-engine",
        title: "Deep Research Engine",
        category: "Deep Research",
        description: "Runs multi-phase research workflows with source scoring.",
        url: "https://github.com/199-biotechnologies/claude-deep-research-skill",
        tags: ["výskum", "multi-phase", "scoring"],
        type: "skill",
        dateAdded: "2026-06-04",
        collection: "claude-skills-prompts-1",
      },
      {
        id: "academic-research-skills",
        title: "Academic Research Skills",
        category: "Academic Writing",
        description: "Supports research, drafting, review, and editing.",
        url: "https://github.com/Imbad0202/academic-research-skills",
        tags: ["akademický výskum", "písanie", "review"],
        type: "skill",
        dateAdded: "2026-06-04",
        collection: "claude-skills-prompts-1",
      },
      {
        id: "vexor-semantic-search",
        title: "Vexor Semantic Search",
        category: "Private Search",
        description: "Enables semantic search through meaning instead of keywords.",
        url: "https://github.com/scarletkc/vexor",
        tags: ["sémantické vyhľadávanie", "súkromné", "embedding"],
        type: "skill",
        dateAdded: "2026-06-04",
        collection: "claude-skills-prompts-1",
      },
      {
        id: "remotion-best-practices",
        title: "Remotion Best Practices",
        category: "Programmatic Video",
        description: "Builds videos in React with captions and MP4 exports.",
        url: "https://github.com/remotion-dev/skills/tree/main/skills/remotion",
        tags: ["Remotion", "React", "video", "MP4"],
        type: "skill",
        dateAdded: "2026-06-04",
        collection: "claude-skills-prompts-1",
      },
      {
        id: "gpt-image-2-skill",
        title: "GPT Image 2 Skill",
        category: "Image Generation",
        description: "Handles image generation, editing, and presets.",
        url: "https://github.com/glebis/claude-skills/tree/main/gpt-image-2",
        tags: ["obrázky", "generovanie", "GPT Image"],
        type: "skill",
        dateAdded: "2026-06-04",
        collection: "claude-skills-prompts-1",
      },
      {
        id: "ai-video-toolkit",
        title: "AI Video Toolkit",
        category: "Video Production",
        description: "Creates AI-powered video production pipelines.",
        url: "https://github.com/digitalsamba/claude-code-video-toolkit",
        tags: ["video", "produkcia", "pipeline"],
        type: "skill",
        dateAdded: "2026-06-04",
        collection: "claude-skills-prompts-1",
      },
      {
        id: "ai-music-album-production",
        title: "AI Music Album Production",
        category: "Music Production",
        description: "Supports AI music creation and mastering workflows.",
        url: "https://github.com/bitwize-music-studio/claude-ai-music-skills",
        tags: ["hudba", "mastering", "AI hudba"],
        type: "skill",
        dateAdded: "2026-06-04",
        collection: "claude-skills-prompts-1",
      },
      {
        id: "generative-media-skills",
        title: "Generative Media Skills",
        category: "Multimodal Media",
        description: "Manages AI image, audio, and video generation.",
        url: "https://github.com/jqueryscript/awesome-claude-code",
        tags: ["multimodal", "obrázky", "audio", "video"],
        type: "skill",
        dateAdded: "2026-06-04",
        collection: "claude-skills-prompts-1",
      },
      {
        id: "dev-browser",
        title: "Dev Browser",
        category: "Browser Automation",
        description: "Enables browser-based AI workflows and QA.",
        url: "https://github.com/jqueryscript/awesome-claude-code",
        tags: ["browser", "automatizácia", "QA"],
        type: "skill",
        dateAdded: "2026-06-04",
        collection: "claude-skills-prompts-1",
      },
      {
        id: "web-scraper",
        title: "Web Scraper",
        category: "Web Scraping",
        description: "Scrapes websites using advanced validation strategies.",
        url: "https://github.com/yfe404/web-scraper",
        tags: ["scraping", "web", "validácia"],
        type: "skill",
        dateAdded: "2026-06-04",
        collection: "claude-skills-prompts-1",
      },
      {
        id: "skill-seekers",
        title: "Skill Seekers",
        category: "Skill Creation",
        description: "Converts repositories and docs into Claude skills.",
        url: "https://github.com/yusufkaraaslan/Skill_Seekers",
        tags: ["tvorba skills", "repozitáre", "dokumentácia"],
        type: "skill",
        dateAdded: "2026-06-04",
        collection: "claude-skills-prompts-1",
      },
      {
        id: "autoresearch-skill",
        title: "Autoresearch Skill",
        category: "Automation / Iteration",
        description: "Runs iterative self-improvement workflows.",
        url: "https://github.com/uditgoenka/autoresearch",
        tags: ["automatizácia", "iterácia", "self-improvement"],
        type: "skill",
        dateAdded: "2026-06-04",
        collection: "claude-skills-prompts-1",
      },
      {
        id: "pm-skills-marketplace",
        title: "PM Skills Marketplace",
        category: "Product Management",
        description: "Supports PRDs, launch strategy, and product workflows.",
        url: "https://github.com/phuryn/pm-skills",
        tags: ["PM", "PRD", "product", "launch"],
        type: "skill",
        dateAdded: "2026-06-04",
        collection: "claude-skills-prompts-1",
      },
      {
        id: "jtbd-interview-tool",
        title: "JTBD Interview Tool",
        category: "Customer Research",
        description: "Converts customer interviews into actionable messaging.",
        url: "https://github.com/glebis/claude-skills/tree/main/skill-studio",
        tags: ["JTBD", "zákazníci", "výskum", "messaging"],
        type: "skill",
        dateAdded: "2026-06-04",
        collection: "claude-skills-prompts-1",
      },
      {
        id: "ai-transformation-discovery",
        title: "AI Transformation Discovery",
        category: "AI Consulting",
        description: "Identifies AI opportunities using consulting frameworks.",
        url: "https://github.com/glebis/claude-skills/tree/main/discovery",
        tags: ["AI konzulting", "príležitosti", "frameworky"],
        type: "skill",
        dateAdded: "2026-06-04",
        collection: "claude-skills-prompts-1",
      },
      {
        id: "superpowers",
        title: "Superpowers",
        category: "Engineering Workflow",
        description: "Forces Claude to think and execute like a senior engineer.",
        url: "https://github.com/obra/superpowers",
        tags: ["inžinierstvo", "senior engineer", "workflow"],
        type: "skill",
        dateAdded: "2026-06-04",
        collection: "claude-skills-prompts-1",
      },
      {
        id: "repomix",
        title: "Repomix",
        category: "Codebase Context",
        description: "Packages repositories into AI-friendly formats.",
        url: "https://github.com/yamadashy/repomix",
        tags: ["repozitár", "kontext", "AI-friendly"],
        type: "skill",
        dateAdded: "2026-06-04",
        collection: "claude-skills-prompts-1",
      },
      {
        id: "antfu-skills",
        title: "Antfu Skills",
        category: "Engineering Skills",
        description: "Production-ready development skills curated by Anthony Fu.",
        url: "https://github.com/antfu/skills",
        tags: ["vývoj", "produkcia", "Anthony Fu"],
        type: "skill",
        dateAdded: "2026-06-04",
        collection: "claude-skills-prompts-1",
      },
      {
        id: "personal-health-assistant",
        title: "Personal Health Assistant",
        category: "Health Data",
        description: "Analyzes medical reports and wellness metrics.",
        url: "https://github.com/BehiSecc/awesome-claude-skills",
        tags: ["zdravie", "medicína", "wellness"],
        type: "skill",
        dateAdded: "2026-06-04",
        collection: "claude-skills-prompts-1",
      },
      {
        id: "dna-analysis",
        title: "DNA Analysis",
        category: "Genome Analysis",
        description: "Processes ancestry and health DNA datasets.",
        url: "https://github.com/BehiSecc/awesome-claude-skills",
        tags: ["DNA", "genóm", "zdravie", "predkovia"],
        type: "skill",
        dateAdded: "2026-06-04",
        collection: "claude-skills-prompts-1",
      },
      {
        id: "beautiful-prose",
        title: "Beautiful Prose",
        category: "Prose / Brand Writing",
        description: "Creates sharper and cleaner English prose.",
        url: "https://github.com/SHADOWPR0/beautiful_prose",
        tags: ["písanie", "próza", "angličtina", "brand"],
        type: "skill",
        dateAdded: "2026-06-04",
        collection: "claude-skills-prompts-1",
      },
    ],
  },
];

export const allKniznicaItems: KniznicaItem[] = kniznicaCollections.flatMap(
  (c) => c.items
);

export const kniznicaCategories = [
  ...new Set(allKniznicaItems.map((i) => i.category)),
];
